# Autogenerated by devscripts/update-version.py

__version__ = '2026.06.16.175612'

RELEASE_GIT_HEAD = '6513cebcbce5754a1a0cd2a8cb5dee8ae8daf12a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'c-basalt/yt-dlp'

ORIGIN = 'c-basalt/yt-dlp'

_pkg_version = '2026.06.16.175612'
